name: Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
  DEBIAN_FRONTEND: noninteractive
  TZ: Etc/UTC


jobs:
  # Ensure unit tests pass
  test:
    name: Run tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, redis-6.1
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer install --dev --no-scripts

      - name: Run tests
        run: |
          ./vendor/bin/pest --testdox-text test-results.txt

      - name: Upload test results as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: pest-test-results
          path: test-results.txt
